Skip qubes creation when not enough info + change some flags + add related validations + refactoring

diff --git a/risk b/risk
--- a/risk
+++ b/risk
@@ -399,12 +399,12 @@ risk_identity_create_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "--no-gw, -G"
+    printf "  %s\n" "--no-tor, -T"
     printf "    Don't create a Whonix TOR gateway\n"
     echo
 
     # :flag.usage
-    printf "  %s\n" "--clone-gw-from TOR_GW"
+    printf "  %s\n" "--clone-tor-from TOR_GW"
     printf "    Instead of creating the TOR gateway from a template, clone an existing TOR\n    AppVM\n"
     echo
 
@@ -477,12 +477,12 @@ risk_identity_equip_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "--no-gw, -G"
+    printf "  %s\n" "--no-tor, -T"
     printf "    Don't create a Whonix TOR gateway\n"
     echo
 
     # :flag.usage
-    printf "  %s\n" "--clone-gw-from TOR_GW"
+    printf "  %s\n" "--clone-tor-from TOR_GW"
     printf "    Instead of creating the TOR gateway from a template, clone an existing TOR\n    AppVM\n"
     echo
 
@@ -1925,7 +1925,7 @@ WHONIX_WS_TEMPLATE=whonix-ws-16
 WHONIX_GW_TEMPLATE=whonix-gw-16
 
 ; Default TemplateVM to use for VPN VMs
-VPN_TEMPLATE=sys-vpn
+VPN_TEMPLATE=
 
 ; Default AppVMs ================================================== #
 ;
@@ -2245,6 +2245,12 @@ function identity.fail_none_active ()
     fi
 }
 
+# identity.fail_other_active exits the program if another identity is already active (opened in vault).
+function identity.fail_other_active ()
+{
+    identity.active && _failure "Another identity ($IDENTITY) is active. Close/slam/stop it and rerun this command"
+}
+
 # identity.fail_unknown exits the program if an identity does not exist in the vault VM.
 
 # $1 - Identity name
@@ -2269,6 +2275,31 @@ function identity.fail_exists ()
     # And check the directory exists
     qvm-run --pass-io "$VAULT_VM" "stat /home/user/.graveyard/$encrypted_identity &>/dev/null"
     [[ $? -eq 0 ]] && _failure "Identity ${IDENTITY} already exists in ${VAULT_VM}"
+}
+
+# identity.set_global_props analyzes the command-line flags and uses some of them
+# to configure stuff about the identity's qubes, such as their colors/prefixes/netvms, etc.
+# Requires access to command-line flags, and needs $IDENTITY to be set.
+function identity.set_global_props ()
+{
+    [[ -z "${IDENTITY}" ]] && return
+
+    local vm_name label
+
+    _warning "Global identity qubes settings"
+
+    # Qube name prefix
+    vm_name="${args['--prefix']-$IDENTITY}"
+    _info "VM prefix:    $name"
+    echo "$vm_name" > "${IDENTITY_DIR}/vm_name"
+
+    # Qube labels (colors)
+    label="${args['--label']-orange}"
+    _info "Label:        $label"
+    echo "$label" > "${IDENTITY_DIR}/vm_label"
+
+    # Default network VM
+    config_get DEFAULT_NETVM > "${IDENTITY_DIR}/net_vm"
 }
 
 # identity.get_args_name either returns the name given as parameter, or
@@ -2927,7 +2958,7 @@ function _catch ()
 # $3 - Label
 function proxy.tor_create ()
 {
-    local gw="${1}-gw"
+    local gw="${1}-tor"
     local netvm="${2-$(config_get DEFAULT_NETVM)}"
     local gw_label="${3-yellow}"
     local gw_template="$(config_get WHONIX_GW_TEMPLATE)"
@@ -2951,7 +2982,7 @@ function proxy.tor_create ()
 # an existing gateway AppVM instead of creating a new one from a Template.
 function proxy.tor_clone ()
 {
-    local gw="${1}-gw"
+    local gw="${1}-tor"
     local gw_clone="$2"
     local netvm="${3-$(config_get DEFAULT_NETVM)}"
     local gw_label="${4-yellow}"
@@ -2983,6 +3014,44 @@ function proxy.tor_clone ()
     _run qvm-tags "$gw" set "$IDENTITY"
     echo "$gw" > "${IDENTITY_DIR}/tor_gw"
     echo "$gw" > "${IDENTITY_DIR}/net_vm"
+}
+
+# proxy.fail_config_tor exits the program if risk lacks some information
+# (which templates/clones to use) when attempting to create a Tor qube.
+function proxy.fail_config_tor ()
+{
+    [[ ${args['--no-tor']} -eq 1 ]] && return
+
+    local template clone netvm
+
+    # Check qubes specified in config or flags.
+    template="$(config_get WHONIX_GW_TEMPLATE)"
+    [[ -n "${args['--clone-tor-from']}" ]] && clone="${args['--clone-tor-from']}"
+
+    # Check those qubes exist
+    if [[ -n ${clone} ]]; then
+        ! qube.exists "${clone}" && _failure "Qube to clone ${clone} does not exist"
+    else
+        ! qube.exists "${template}" && _failure "Qube template ${template} does not exist"
+    fi
+}
+
+# proxy.skip_tor_create returns 0 when there not enough information in the configuration
+# file or in command flags for creating a new TOR qube (no templates/clones indicated, etc).
+# Needs access to command-line flags
+function proxy.skip_tor_create ()
+{
+    [[ ${args['--no-tor']} -eq 1 ]] && return 0
+
+    local template clone netvm
+
+    template="$(config_get WHONIX_GW_TEMPLATE)"
+    [[ -n "${args['--clone-tor-from']}" ]] && clone="${args['--clone-tor-from']}"
+
+    [[ -z ${template} && -z ${clone} ]] && \
+        _info "Skipping TOR gateway: no TemplateVM/AppVM specified in config or flags" && return 0
+
+    return 1
 }
 
 # src/lib/utils.sh
@@ -3113,6 +3182,16 @@ validate_valid_vaultvm () {
     fi
 }
 
+# validate_netvm fails if the specified VM does not provide network.
+validate_netvm ()
+{
+    local netvm="${1}"
+
+    if [[ $(qvm-prefs "${netvm}" provides_network) == False ]]; then
+        echo "Qube ${netvm} is specified as netvm, but does not provide network."
+    fi
+}
+
 # src/lib/vm.sh
 
 #
@@ -3123,6 +3202,24 @@ validate_valid_vaultvm () {
 # Functions starting with an underscore
 # give information and values related to VMs,
 #
+
+# qube.exists returns 0 if the qube is found, or 1 if not.
+# $1 - Qube name
+function qube.exists ()
+{
+    vm=""
+    for item in $(qvm-ls --raw-list | grep -v dom0)
+    do
+        if [ "${item}" == "${1}" ]; then
+            vm=${1}
+        fi
+    done
+    if [ ${#vm} -eq 0 ]; then
+        return 1
+    fi
+
+    return 0
+}
 
 # Returns the name of the identity to which a VM belongs.
 # $1 - Qube name
@@ -3504,6 +3601,44 @@ function proxy.vpn_clone ()
     echo "$gw" >> "${IDENTITY_DIR}/proxy_vms"
 }
 
+# proxy.fail_config_vpn exits the program if risk lacks some information
+# (which templates/clones to use) when attempting to create a VPN qube.
+function proxy.fail_config_vpn ()
+{
+    local template clone netvm
+
+    # Check qubes specified in config or flags.
+    template="$(config_get VPN_TEMPLATE)"
+    if [[ ${args['--clone']} -eq 1 ]]; then
+        [[ -n ${args['--from']} ]] && clone=${args['--from']} || clone=$(config_get VPN_VM)
+    fi
+
+    # Check those qubes exist
+    if [[ -n ${clone} ]]; then
+        ! qube.exists "${clone}" && _failure "Qube to clone ${clone} does not exist"
+    else
+        ! qube.exists "${template}" && _failure "Qube template ${template} does not exist"
+    fi
+}
+
+# proxy.skip_vpn_create returns 0 when there not enough information in the configuration
+# file or in command flags for creating a new VPN qube (no templates/clones indicated, etc).
+# Needs access to command-line flags
+function proxy.skip_vpn_create ()
+{
+    local template clone netvm
+
+    # Check qubes specified in config or flags.
+    template="$(config_get VPN_TEMPLATE)"
+    if [[ ${args['--clone']} -eq 1 ]]; then
+        [[ -n ${args['--from']} ]] && clone=${args['--from']} || clone=$(config_get VPN_VM)
+    fi
+
+    [[ -z ${template} && -z ${clone} ]] && return 0
+
+    return 1
+}
+
 # proxy.vpn_import_configs browses for one or more (as zip) VPN client configurations
 # in another VM, import them in our VPN VM, and run the setup wizard if there is more
 
@@ -3667,6 +3802,39 @@ function web.browser_clone ()
     echo "${web}" > "${IDENTITY_DIR}/browser_vm"
 }
 
+# web.fail_config_browser exits the program if risk lacks some information
+# (which templates/clones to use) when attempting to create a browser qube.
+function web.fail_config_browser ()
+{
+    local template clone netvm
+
+    # Check qubes specified in config or flags.
+    template="$(config_get WHONIX_WS_TEMPLATE)"
+    [[ -n "${args['--clone-web-from']}" ]] && clone="${args['--clone-web-from']}"
+
+    # Check those qubes exist
+    if [[ -n ${clone} ]]; then
+        ! qube.exists "${clone}" && _failure "Qube to clone ${clone} does not exist"
+    else
+        ! qube.exists "${template}" && _failure "Qube template ${template} does not exist"
+    fi
+}
+
+# proxy.skip_browser_create returns 0 when there not enough information in the configuration
+# file or in command flags for creating a new browser qube (no templates/clones indicated, etc).
+# Needs access to command-line flags
+function web.skip_browser_create ()
+{
+    local template clone netvm
+
+    # Check qubes specified in config or flags.
+    template="$(config_get WHONIX_WS_TEMPLATE)"
+    [[ -n "${args['--clone-web-from']}" ]] && clone="${args['--clone-web-from']}"
+
+    [[ -z ${template} && -z ${clone} ]] && \
+        _info "Skipping browser qube: no TemplateVM/AppVM specified in config or flags" && return 0
+}
+
 # Create a split-browser VM from a template
 function web.split_backend_create ()
 {
@@ -3695,6 +3863,14 @@ function web.split_backend_clone ()
     qvm-prefs "$web" netvm None
 
     qvm-tags "$web" set "$IDENTITY"
+}
+
+# web.fail_config_split_backend exits the program if risk lacks some information
+# (which templates/clones to use) when attempting to create a split-browser qube.
+function web.fail_config_split_backend ()
+{
+    local template clone
+
 }
 
 # web.browser_set_split_dispvm updates the default disposable VM
@@ -3745,6 +3921,14 @@ function web.browser_unset_split_dispvm ()
     _info "Bookmarks: removed"
     _run_qube "${split_backend}" "qvm-copy-to-vm ${VAULT_VM} ${bookmarks_backend_path}"
     _run_qube "${split_backend}" "shred -u ${bookmarks_backend_path}"
+}
+
+# web.no_split_backend returns 0 if there is no split-browser backend
+
+# qube specified in the configuration/flags, or 1 if one is found.
+function web.no_split_backend ()
+{
+    echo -n
 }
 
 # ========================================================================================
@@ -4073,36 +4257,34 @@ risk_identity_create_command() {
 
   local other_args
 
-  # 0 - Safety checks
+  # 0 - Safety checks --------------------------------------------------------------
+
+  # The identity should not exist, and none other should be active.
   identity.set "${identity}"
-
-  if identity.active ; then
-      _failure "Another identity ($IDENTITY) is active. Close/slam/stop it and rerun this command"
-  fi
-
+  identity.fail_other_active
   identity.fail_exists
 
-  # 1 - Create identity in vault
+  # 1 - Create identity in vault ---------------------------------------------------
   _in_section "identity" 8 && _info "Creating identity in vault"
 
   [[ -n "${args['expiry_date']}" ]] && other_args+=( "${args['expiry_date']}" )
   [[ -n "$pendrive" ]] && other_args=(--backup "$pendrive")
   [[ "${args['--burner']}" -eq 1 ]] && other_args+=( --burner )
 
-  _run_qube_term "$VAULT_VM" risks identity create "$name" "$email" "${other_args[@]}"
+  _run_qube_term "$VAULT_VM" risks identity create "'$name'" "$email" "${other_args[@]}"
   _catch "Failed to create identity in vault"
 
-  _run_qube_term "$VAULT_VM" risks identity open "$name"
+  _run_qube_term "$VAULT_VM" risks identity open "$identity"
   _catch "Failed to open identity in vault"
 
   # If the user only wanted to create the identity in the vault, exit.
   if [[ ${args['--vault-only']} -eq 1 ]] ; then
       _info "Skipping infrastructure setup"
-      _success "Successfully created identity $IDENTITY"
+      _success "Successfully created identity $identity"
       exit
   fi
 
-  # 2 - Create all default qubes and related settings for identity.
+  # 2 - Create all default qubes ---------------------------------------------------
   risk_identity_equip_command
 
 }
@@ -4120,59 +4302,39 @@ risk_identity_equip_command() {
   local web_netvm         # NetVM for the Web browser VM
   local clone             # A variable that might be overritten several times, used to assign a VM to clone.
 
-  # Propagate the identity and its settings (in the script only)
-  identity.set "${args['identity']}"
-
-  # Identity checks and basic setup ==========================================
-
+  # 1 - Identity basic setup
+  identity.set "${name}"
   identity.fail_unknown "$IDENTITY"
 
-  _info "Creating qubes for identity $IDENTITY"
+  _in_section "risk" 8 && _info "Creating qubes for identity $IDENTITY"
 
-  # Make a directory for this identity, and store the associated VM name
-  _in_section "network" 8 && echo && _warning "Global identity qubes settings"
   [[ -e ${IDENTITY_DIR} ]] || mkdir -p "$IDENTITY_DIR"
+  identity.set_global_props
 
-  # If the user wants to use a different vm_name for the VMs
-  vm_name="${args['--prefix']-$IDENTITY}"
-  _info "VM prefix:    $name"
-  echo "$vm_name" > "${IDENTITY_DIR}/vm_name"
-
-  label="${args['--label']-orange}"
-  _info "Label:        $label"
-  echo "$vm_name" > "${IDENTITY_DIR}/vm_label"
-
-  # Prepare the root NetVM for this identity
-  config_get DEFAULT_NETVM > "${IDENTITY_DIR}/net_vm"
-
-  # Network VMs ==============================================================
+  # 2 - Network VMs
   _in_section "network" && echo && _warning "Creating network VMs"
   gw_netvm="$(cat "${IDENTITY_DIR}/net_vm")"
 
-  # 1 - Tor gateway, if not explicitly disabled
-  if [[ ${args['--no-gw']} -eq 0 ]]; then
-      if [[ -n ${args['--clone-gw-from']} ]]; then
-          clone="${args['--clone-gw-from']}"
+  if ! proxy.skip_tor_create; then
+      if [[ -n ${args['--clone-tor-from']} ]]; then
+          clone="${args['--clone-tor-from']}"
           proxy.tor_clone "$vm_name" "$clone" "$gw_netvm" "$label"
       else
           proxy.tor_create "$vm_name" "$gw_netvm" "$label"
       fi
-  else
-      _info "Skipping TOR gateway"
   fi
 
-  # Browser VMs ==============================================================
+  # 3 - Browser VMs
   _in_section "web" && echo && _warning "Creating browsing VMs"
   web_netvm="$(cat "${IDENTITY_DIR}/net_vm")"
 
-  # Browser VMs are disposable, but we make a template for this identity,
-  # since we might  either modify stuff in there, and we need them at least
-  # to have a different network route.
-  if [[ -n ${args['--clone-web-from']} ]]; then
-      clone="${args['--clone-web-from']}"
-      web.browser_clone "$vm_name" "$clone" "$web_netvm" "$label"
-  else
-      web.browser_create "$vm_name" "$web_netvm" "$label"
+  if ! web.skip_browser_create; then
+      if [[ -n ${args['--clone-web-from']} ]]; then
+          clone="${args['--clone-web-from']}"
+          web.browser_clone "$vm_name" "$clone" "$web_netvm" "$label"
+      else
+          web.browser_create "$vm_name" "$web_netvm" "$label"
+      fi
   fi
 
   # Per-identity bookmarks file in vault management tomb.
@@ -5803,20 +5965,20 @@ risk_identity_create_parse_requirements() {
         ;;
 
       # :flag.case
-      --no-gw | -G)
+      --no-tor | -T)
         # :flag.conflicts
-        if [[ -n "${args['--clone-gw-from']:-}" ]]; then
-          printf "conflicting options: %s cannot be used with %s\n" "$key" "--clone-gw-from" >&2
+        if [[ -n "${args['--clone-tor-from']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--clone-tor-from" >&2
           exit 1
         fi
 
         # :flag.case_no_arg
-        args['--no-gw']=1
+        args['--no-tor']=1
         shift
         ;;
 
       # :flag.case
-      --clone-gw-from)
+      --clone-tor-from)
         # :flag.conflicts
         if [[ -n "${args['--no-gw']:-}" ]]; then
           printf "conflicting options: %s cannot be used with %s\n" "$key" "--no-gw" >&2
@@ -5826,11 +5988,11 @@ risk_identity_create_parse_requirements() {
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
 
-          args['--clone-gw-from']="$2"
+          args['--clone-tor-from']="$2"
           shift
           shift
         else
-          printf "%s\n" "--clone-gw-from requires an argument: --clone-gw-from TOR_GW" >&2
+          printf "%s\n" "--clone-tor-from requires an argument: --clone-tor-from TOR_GW" >&2
           exit 1
         fi
         ;;
@@ -5953,20 +6115,20 @@ risk_identity_equip_parse_requirements() {
         ;;
 
       # :flag.case
-      --no-gw | -G)
+      --no-tor | -T)
         # :flag.conflicts
-        if [[ -n "${args['--clone-gw-from']:-}" ]]; then
-          printf "conflicting options: %s cannot be used with %s\n" "$key" "--clone-gw-from" >&2
+        if [[ -n "${args['--clone-tor-from']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--clone-tor-from" >&2
           exit 1
         fi
 
         # :flag.case_no_arg
-        args['--no-gw']=1
+        args['--no-tor']=1
         shift
         ;;
 
       # :flag.case
-      --clone-gw-from)
+      --clone-tor-from)
         # :flag.conflicts
         if [[ -n "${args['--no-gw']:-}" ]]; then
           printf "conflicting options: %s cannot be used with %s\n" "$key" "--no-gw" >&2
@@ -5976,11 +6138,11 @@ risk_identity_equip_parse_requirements() {
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
 
-          args['--clone-gw-from']="$2"
+          args['--clone-tor-from']="$2"
           shift
           shift
         else
-          printf "%s\n" "--clone-gw-from requires an argument: --clone-gw-from TOR_GW" >&2
+          printf "%s\n" "--clone-tor-from requires an argument: --clone-tor-from TOR_GW" >&2
           exit 1
         fi
         ;;
@@ -6695,6 +6857,11 @@ risk_vpn_create_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_netvm "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--netvm, -n VM" "$(validate_netvm "$2")" >&2
+            exit 1
+          fi
 
           args['--netvm']="$2"
           shift
@@ -6787,6 +6954,11 @@ risk_vpn_setup_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_netvm "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--netvm, -n VM" "$(validate_netvm "$2")" >&2
+            exit 1
+          fi
 
           args['--netvm']="$2"
           shift
